CREATE TABLE IF NOT EXISTS EMAIL_TRACKING(
    EMAIL_ID TEXT PRIMARY KEY NOT NULL,
    USER_ID INT NOT NULL,
    FLIGHT_LINK TEXT NOT NULL,
    FOREIGN KEY (USER_ID, FLIGHT_LINK) REFERENCES DEAL_MAPPING
)