CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL TEXT UNIQUE NOT NULL,
    RELEVANT_AIRPORTS TEXT[],
    SUBSCRIBED_COUNTRIES TEXT[],
    CONFIG JSON,
    THRESHOLD INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    CHECK (THRESHOLD >= 0 AND THRESHOLD <= 100)
);

CREATE TABLE IF NOT EXISTS DEALS(
    DESTINATION_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    COUNTRY TEXT NOT NULL,
    PRICE FLOAT NOT NULL,
    AVERAGE_PRICE FLOAT,
    DISCOUNT_PERCENTAGE FLOAT,
    FLIGHT_LINK TEXT NOT NULL,
    SERP_API_FLIGHT_LINK TEXT NOT NULL,
    THUMBNAIL TEXT NOT NULL,
    START_DATE TEXT NOT NULL,
    END_DATE TEXT,
    DEPARTURE_AIRPORT_CODE TEXT NOT NULL,
    ARRIVAL_AIRPORT_CODE TEXT NOT NULL,
    FLIGHT_DURATION INT NOT NULL,
    STOPS INT NOT NULL,
    AIRLINE TEXT,
    AIRLINE_CODE TEXT,
    DESCRIPTION TEXT,
    HIGHLIGHTS TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (FLIGHT_LINK)
);

CREATE TABLE IF NOT EXISTS DEAL_MAPPING(
    USER_ID INT NOT NULL,
    FLIGHT_LINK TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (USER_ID, FLIGHT_LINK),
    FOREIGN KEY (USER_ID) REFERENCES USERS,
    FOREIGN KEY (FLIGHT_LINK) REFERENCES DEALS
)