CREATE TABLE IF NOT EXISTS EMAIL_TRACKING(
    EMAIL_ID TEXT NOT NULL,
    USER_ID INT NOT NULL,
    FLIGHT_LINK TEXT NOT NULL,
    PRIMARY KEY (EMAIL_ID, USER_ID, FLIGHT_LINK),
    FOREIGN KEY (USER_ID, FLIGHT_LINK) REFERENCES DEAL_MAPPING
)