CREATE TABLE IF NOT EXISTS EMAIL_TRACKING(
    USER_ID INT,
    FLIGHT_LINK TEXT,
    EMAIL_ID TEXT NOT NULL,
    PRIMARY KEY (USER_ID, FLIGHT_LINK, EMAIL_ID),
    FOREIGN KEY (USER_ID, FLIGHT_LINK) REFERENCES DEAL_MAPPING
)