package db

// User queries
const addUserQuery = `INSERT INTO USERS(EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD) VALUES(@EMAIL, @RELEVANT_AIRPORTS, @SUBSCRIBED_COUNTRIES, @CONFIG, @THRESHOLD) RETURNING ID`
const updateUserQuery = `UPDATE USERS 
						SET
						    EMAIL=@EMAIL,
						    RELEVANT_AIRPORTS=@RELEVANT_AIRPORTS,
						    SUBSCRIBED_COUNTRIES=@SUBSCRIBED_COUNTRIES,
						    CONFIG=@CONFIG,
						    THRESHOLD=@THRESHOLD
						WHERE ID=@ID
                 		`
const findUserQuery = `SELECT ID, EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD, CREATED_AT FROM USERS WHERE ID=$1`
const deleteUserQuery = `DELETE FROM USERS WHERE ID=$1`

// Deal queries
const addDealQuery = `INSERT INTO DEALS(
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
                  			ARRIVAL_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						)
						VALUES(
							@DESTINATION_ID,
							@NAME,
							@COUNTRY,
							@PRICE,
							@AVERAGE_PRICE,
							@DISCOUNT_PERCENTAGE,
							@FLIGHT_LINK,
							@SERP_API_FLIGHT_LINK,
							@THUMBNAIL,
							@START_DATE,
							@END_DATE,
							@DEPARTURE_AIRPORT_CODE,
						    @ARRIVAL_AIRPORT_CODE,
							@FLIGHT_DURATION,
							@STOPS,
							@AIRLINE,
							@AIRLINE_CODE,
							@DESCRIPTION,
							@HIGHLIGHTS  
						)
						ON CONFLICT DO NOTHING
						`

const mapUserAndDeal = `INSERT INTO DEAL_MAPPING(
							 USER_ID,
							 FLIGHT_LINK
                         )
    					VALUES (
						    @USER_ID,
							@FLIGHT_LINK
						)
`
const getDealsQuery = `SELECT
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							DEALS.FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
							ARRIVAL_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						FROM DEALS
						INNER JOIN DEAL_MAPPING
						ON DEALS.FLIGHT_LINK=DEAL_MAPPING.FLIGHT_LINK AND USER_ID=$1
`
