package db

// User queries
const addUserQuery = `INSERT INTO USERS(EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD) VALUES(@EMAIL, @RELEVANT_AIRPORTS, @SUBSCRIBED_COUNTRIES, @CONFIG, @THRESHOLD)`
const updateUserQuery = `UPDATE USERS 
						SET
						    RELEVANT_AIRPORTS=@RELEVANT_AIRPORTS,
						    SUBSCRIBED_COUNTRIES=@SUBSCRIBED_COUNTRIES,
						    CONFIG=@CONFIG,
						    THRESHOLD=@THRESHOLD
						WHERE EMAIL=@EMAIL
                 		`
const findUserQueryId = `SELECT EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD, CREATED_AT FROM USERS WHERE ID=$1`
const findUserQueryEmail = `SELECT EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD, CREATED_AT FROM USERS WHERE EMAIL=$1`
const deleteUserQueryID = `DELETE FROM USERS WHERE ID=$1`
const deleteUserQueryEmail = `DELETE FROM USERS WHERE EMAIL=$1`

// Deal queries
const addDealQuery = `INSERT INTO DEALS (
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						)
						VALUES(
							DESTINATION_ID=@DESTINATION_ID,
							NAME=@NAME,
							COUNTRY=@COUNTRY,
							PRICE=@PRICE,
							AVERAGE_PRICE=@AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE=@DISCOUNT_PERCENTAGE,
							FLIGHT_LINK=@FLIGHT_LINK,
							SERP_API_FLIGHT_LINK=@SERP_API_FLIGHT_LINK,
							THUMBNAIL=@THUMBNAIL,
							START_DATE=@START_DATE,
							END_DATE=@END_DATE,
							DEPARTURE_AIRPORT_CODE=@DEPARTURE_AIRPORT_CODE,
							FLIGHT_DURATION=@FLIGHT_DURATION,
							STOPS=@STOPS,
							AIRLINE=@AIRLINE,
							AIRLINE_CODE=@AIRLINE_CODE,
							DESCRIPTION=@DESCRIPTION,
							HIGHLIGHTS=@HIGHLIGHTS  
						)
						`

const getDealsQuery = `SELECT
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						FROM DEALS
`
