package db

// User queries
const addUserQuery = `INSERT INTO USERS(EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD) VALUES(@EMAIL, @RELEVANT_AIRPORTS, @SUBSCRIBED_COUNTRIES, @CONFIG, @THRESHOLD) RETURNING ID`
const updateUserQuery = `UPDATE USERS 
						SET
						    EMAIL=@EMAIL,
						    RELEVANT_AIRPORTS=@RELEVANT_AIRPORTS,
						    SUBSCRIBED_COUNTRIES=@SUBSCRIBED_COUNTRIES,
						    CONFIG=@CONFIG,
						    THRESHOLD=@THRESHOLD
						WHERE ID=@ID
                 		`
const findUserQuery = `SELECT ID, EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD, CREATED_AT FROM USERS WHERE ID=$1`
const getAllUsersQuery = `SELECT ID, EMAIL, RELEVANT_AIRPORTS, SUBSCRIBED_COUNTRIES, CONFIG, THRESHOLD, CREATED_AT FROM USERS`
const deleteUserQuery = `DELETE FROM USERS WHERE ID=$1`

// Deal queries
const getDealQuery = `SELECT
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
							ARRIVAL_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						FROM DEALS
						WHERE FLIGHT_LINK=$1
						`
const getDealForUserQuery = `SELECT 
    								USER_ID 
							FROM DEAL_MAPPING 
							INNER JOIN DEALS
							ON DEAL_MAPPING.FLIGHT_LINK=DEALS.FLIGHT_LINK
							WHERE 
							    USER_ID=@USER_ID AND
							    NAME=@NAME AND
							    COUNTRY=@COUNTRY AND
							    PRICE=@PRICE AND
							    START_DATE=@START_DATE AND
							    END_DATE=@END_DATE AND
							    DEPARTURE_AIRPORT_CODE=@DEPARTURE_AIRPORT_CODE AND
							    ARRIVAL_AIRPORT_CODE=@ARRIVAL_AIRPORT_CODE AND
							    FLIGHT_DURATION=@FLIGHT_DURATION AND
							    STOPS=@STOPS
    						`
const addDealQuery = `INSERT INTO DEALS(
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
                  			ARRIVAL_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						)
						VALUES(
							@DESTINATION_ID,
							@NAME,
							@COUNTRY,
							@PRICE,
							@AVERAGE_PRICE,
							@DISCOUNT_PERCENTAGE,
							@FLIGHT_LINK,
							@SERP_API_FLIGHT_LINK,
							@THUMBNAIL,
							@START_DATE,
							@END_DATE,
							@DEPARTURE_AIRPORT_CODE,
						    @ARRIVAL_AIRPORT_CODE,
							@FLIGHT_DURATION,
							@STOPS,
							@AIRLINE,
							@AIRLINE_CODE,
							@DESCRIPTION,
							@HIGHLIGHTS  
						)
						ON CONFLICT DO NOTHING 
						`

const mapUserAndDeal = `INSERT INTO DEAL_MAPPING(USER_ID, FLIGHT_LINK) VALUES (@USER_ID, @FLIGHT_LINK)
`
const getDealsQuery = `SELECT
							DESTINATION_ID,
							NAME,
							COUNTRY,
							PRICE,
							AVERAGE_PRICE,
							DISCOUNT_PERCENTAGE,
							DEALS.FLIGHT_LINK,
							SERP_API_FLIGHT_LINK,
							THUMBNAIL,
							START_DATE,
							END_DATE,
							DEPARTURE_AIRPORT_CODE,
							ARRIVAL_AIRPORT_CODE,
							FLIGHT_DURATION,
							STOPS,
							AIRLINE,
							AIRLINE_CODE,
							DESCRIPTION,
							HIGHLIGHTS
						FROM DEALS
						INNER JOIN DEAL_MAPPING
						ON DEALS.FLIGHT_LINK=DEAL_MAPPING.FLIGHT_LINK AND USER_ID=$1
						`

// Email Tracking queries
const addEmailTrackingQuery = `INSERT INTO EMAIL_TRACKING(EMAIL_ID, USER_ID, FLIGHT_LINK) VALUES (@EMAIL_ID, @USER_ID, @FLIGHT_LINK)`

const getUnsentEmailsQuery = `SELECT
								DEAL_MAPPING.USER_ID,
								DEAL_MAPPING.FLIGHT_LINK
	                      FROM DEAL_MAPPING
						  LEFT JOIN EMAIL_TRACKING
						  ON DEAL_MAPPING.USER_ID=EMAIL_TRACKING.USER_ID AND DEAL_MAPPING.FLIGHT_LINK=EMAIL_TRACKING.FLIGHT_LINK
						  WHERE EMAIL_TRACKING.EMAIL_ID IS NULL
						  `
